name: Test

on: 
  repository_dispatch:
    types: [test]

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print the message to STDOUT
        run: echo  The message is ${{ github.event.client_payload.example-key }} 