name: Test

on: 
  repository_dispatch:
    types: [test]

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if: ${{github.event.client_payload.show}}
    steps:
      - name: Print the message to STDOUT
        run: echo  The message is ${{ github.event.client_payload.message }} 